llm_providers:
  ollama:
    available_models:
    - display_name: gemma3:1b-it-fp16
      api_name: gemma3:1b-it-fp16
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - gemma3:12b-it-qat
  openai:
    available_models:
    - display_name: o4-mini
      api_name: o4-mini
      tags:
      - Reasoning
      reasoning_level: high
      enabled: true
    - display_name: GPT-4.1 Nano
      api_name: gpt-4.1-nano-2025-04-14
      tags:
      - General
      enabled: true
    enabled: true
    enabled_models:
    - o4-mini
    - gpt-4.1-nano-2025-04-14
  gemini:
    available_models:
    - display_name: Gemini 2.5 Pro
      api_name: gemini-2.5-pro
      tags:
      - General
      enabled: true
    - display_name: Gemini 2.5 Flash Lite
      api_name: gemini-2.5-flash-lite
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - gemini-2.5-flash-lite
  claude:
    available_models:
    - display_name: Claude 3.5 Haiku
      api_name: claude-3-5-haiku-latest
      tags:
      - General
      enabled: true
    - display_name: Claude 4 Sonnet
      api_name: claude-sonnet-4-0
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - claude-3-5-haiku-latest
    - claude-sonnet-4-0
analysis:
  enable_resume: false
  resume_validation: false
  reviews_to_analyze: 2
  api_retries: 3
  api_retry_delay: 1
  ollama_retries: 1
  ollama_retry_delay: 5
  periodic_save_interval: 10
  skip_scraping: false
  validate_raw_reviews: false
  prompt_file: new_prompt.txt
  api_batch_size: 5
fetching:
  reviews_per_app: 100
  max_requests_per_app: 5
  language: all
  num_per_page: 100
  enable_complete_scraping: true
  scraping_timeout: 3600
  start_date: ''
  end_date: ''
  max_empty_attempts: 3
  initial_backoff_time: 1
  max_backoff_time: 10
  error_backoff_time: 30
filtering:
  min_review_length: 50
  min_playtime_hours: 0
advanced_filtering:
  max_playtime_hours: 100000
  max_review_length: 10000
  min_votes_up: 0
  early_access_only: false
  exclude_early_access: false
  verified_purchase_only: false
  exclude_received_free: false
file_paths:
  raw_output_folder: output/raw
  analysed_output_folder: output/analysed
  summary_output_folder: output/summary
files:
  raw_reviews_suffix: _reviews.csv
  analysed_reviews_suffix: _analyzed.csv
  summary_output_filename: topic_analysis_summary.json
validation:
  validate_app_ids: true
  validate_models: true
  validate_dates: true
  validate_prompts: true
appearance:
  theme: System
  scaling: 100%
app_ids:
- 526870
max_reviews: 1000
debug_mode: false
selected_apps:
- appid: 526870
  name: Satisfactory
