llm_providers:
  ollama:
    available_models:
    - display_name: gemma3:1b-it-fp16
      api_name: gemma3:1b-it-fp16
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models: []
  openai:
    available_models:
    - display_name: o4-mini
      api_name: o4-mini
      tags:
      - Reasoning
      reasoning_level: high
      enabled: true
    - display_name: GPT-4.1 Nano
      api_name: gpt-4.1-nano-2025-04-14
      tags:
      - Fast
      - Lite
      enabled: true
    - display_name: o3
      api_name: o3
      tags:
      - Reasoning
      reasoning_level: high
      enabled: true
    enabled: true
    enabled_models:
    - o3
  gemini:
    available_models:
    - display_name: Gemini 2.5 Pro
      api_name: gemini-2.5-pro
      tags:
      - General
      enabled: true
    - display_name: Gemini 2.5 Flash Lite
      api_name: gemini-2.5-flash-lite
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - gemini-2.5-flash-lite
  claude:
    available_models:
    - display_name: Claude 3.5 Haiku
      api_name: claude-3-5-haiku-latest
      tags:
      - General
      enabled: true
    - display_name: Claude 4 Sonnet
      api_name: claude-sonnet-4-0
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - claude-3-5-haiku-latest
    - claude-sonnet-4-0
analysis:
  reviews_to_analyze: 20
  api_retries: 3
  api_retry_delay: 1
  api_batch_size: 5
  enable_resume: true
  skip_scraping: true
  prompt_file: prompt.txt
fetching:
  reviews_per_app: 110
  language: english
  scraping_timeout: 3600
  enable_complete_scraping: false
filtering:
  min_review_length: 50
  min_playtime_hours: 0
advanced_filtering:
  min_votes_up: 0
  early_access_only: false
  verified_purchase_only: false
file_paths:
  raw_output_folder: output/raw
  analysed_output_folder: output/analysed
  summary_output_folder: output/summary
files:
  raw_reviews_suffix: _reviews.csv
  analysed_reviews_suffix: _analyzed.csv
  summary_output_filename: topic_analysis_summary.json
validation:
  validate_app_ids: true
  validate_models: true
appearance:
  theme: System
  scaling: 100%
app_ids:
- 22370
max_reviews: 1000
debug_mode: false
selected_apps:
- appid: 22370
  name: Fallout 3 - Game of the Year Edition
