llm_providers:
  ollama:
    available_models:
    - display_name: gpt-oss:120b
      api_name: gpt-oss:120b
      tags:
      - General
      enabled: true
    - display_name: gpt-oss:20b
      api_name: gpt-oss:20b
      tags:
      - General
      enabled: true
    - display_name: phi4:14b
      api_name: phi4:14b
      tags:
      - General
      enabled: true
    - display_name: granite3.3:8b
      api_name: granite3.3:8b
      tags:
      - General
      enabled: true
    - display_name: qwen3:14b-q4_K_M
      api_name: qwen3:14b-q4_K_M
      tags:
      - General
      enabled: true
    - display_name: gemma3:12b-it-qat
      api_name: gemma3:12b-it-qat
      tags:
      - General
      enabled: true
    enabled: true
    enabled_models:
    - phi4:14b
    - granite3.3:8b
  openai:
    available_models:
    - display_name: o4-mini
      api_name: o4-mini
      tags:
      - Reasoning
      reasoning_level: high
      enabled: true
    - display_name: GPT-4.1 Nano
      api_name: gpt-4.1-nano-2025-04-14
      tags:
      - Fast
      - Lite
      enabled: true
    - display_name: o3
      api_name: o3
      tags:
      - Reasoning
      reasoning_level: high
      enabled: true
    enabled: true
    enabled_models:
    - gpt-4.1-nano-2025-04-14
  gemini:
    available_models:
    - display_name: Gemini 2.5 Pro
      api_name: gemini-2.5-pro
      tags:
      - General
      enabled: true
    - display_name: Gemini 2.5 Flash Lite
      api_name: gemini-2.5-flash-lite
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - gemini-2.5-flash-lite
  claude:
    available_models:
    - display_name: Claude 3.5 Haiku
      api_name: claude-3-5-haiku-latest
      tags:
      - Lite
      - Fast
      enabled: true
    - display_name: Claude 4 Sonnet
      api_name: claude-sonnet-4-0
      tags:
      - General
      enabled: true
    enabled: false
    enabled_models:
    - claude-3-5-haiku-latest
    - claude-sonnet-4-0
analysis:
  reviews_to_analyze: 5
  api_retries: 3
  api_retry_delay: 1
  api_batch_size: 5
  enable_resume: true
  skip_scraping: false
  prompt_file: prompt.txt
fetching:
  reviews_per_app: 330
  language: english
  scraping_timeout: 3600
  enable_complete_scraping: false
filtering:
  min_review_length: 50
  min_playtime_hours: 0
advanced_filtering:
  min_votes_up: 0
  early_access_only: false
  verified_purchase_only: false
file_paths:
  raw_output_folder: output/raw
  analysed_output_folder: output/analysed
  summary_output_folder: output/summary
files:
  raw_reviews_suffix: _reviews.csv
  analysed_reviews_suffix: _analyzed.csv
  summary_output_filename: topic_analysis_summary.json
validation:
  validate_app_ids: true
  validate_models: true
appearance:
  theme: System
  scaling: 100%
app_ids:
- 377160
max_reviews: 1000
debug_mode: false
selected_apps:
- appid: 377160
  name: Fallout 4
